pool:
  name: Default

steps:

- checkout: self
  fetchDepth: 0

- script: |
    "D:\Downloads\vsts-agent-win-x86-4.273.0\_work\_tasks\SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055\7.4.2\sonar-scanner\bin\sonar-scanner.bat" ^
      -Dsonar.projectKey=Taskflow ^
      -Dsonar.projectName=Taskflow ^
      -Dsonar.sources=. ^
      -Dsonar.host.url=$(SONAR_HOST_URL) ^
      -Dsonar.token=$(SONAR_TOKEN) ^
      -Dsonar.scm.provider=git
  displayName: Run SonarQube Analysis

- script: docker compose build
  displayName: Build Docker Images

- script: docker compose up -d
  displayName: Run Containers

- script: docker ps
  displayName: Check Running Containers