trigger:
- main

pool:
  name: Default

steps:

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'demoTaskflow'
    cliProjectName: 'demoTaskflow'
    cliSources: '.'

- task: SonarQubeAnalyze@7

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'

- script: docker compose build
  displayName: Build Docker Images

- script: docker compose up -d
  displayName: Run Containers

- script: docker ps
  displayName: Check Running Containers