version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@cluster0.mongodb.net/?retryWrites=true&w=majority

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
